# Generated by Django 5.2.17 on 2026-09-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ad_distinguished_name",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="AD distinguished name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ad_managed",
            field=models.BooleanField(
                default=False,
                help_text="Created or linked by the AD sync: IAM-Users membership controls the account.",
                verbose_name="Managed by AD",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ad_object_guid",
            field=models.UUIDField(
                blank=True,
                help_text="objectGUID of the account in on-prem Active Directory; set by the AD sync.",
                null=True,
                unique=True,
                verbose_name="AD objectGUID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ad_sam_account_name",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="AD account name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ad_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last AD sync"
            ),
        ),
    ]
