# Generated by Django 5.2.17 on 2026-09-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_ad_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="entra_managed",
            field=models.BooleanField(
                default=False,
                help_text="Created or linked by the Entra ID sync: its user group controls the account.",
                verbose_name="Managed by Entra ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="entra_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Entra ID sync"
            ),
        ),
    ]
