# Generated by Django 5.2.17 on 2026-09-22 16:05

import apps.people.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_dynamic_ad_groups"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The exclusion constraints below compare integer foreign keys inside a GiST
        # index, which is what btree_gist provides. A trusted extension since PostgreSQL 13,
        # so the database owner the deployments create can install it without superuser.
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="PersonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_external",
                    models.BooleanField(
                        default=True,
                        help_text="Not employed by the organization. Open-ended assignments of an external type are listed for review, since nothing else will end them.",
                        verbose_name="External",
                    ),
                ),
                (
                    "requires_end_date",
                    models.BooleanField(
                        default=False,
                        help_text="Every assignment of this type must carry an end date.",
                    ),
                ),
                (
                    "requires_sponsor",
                    models.BooleanField(
                        default=False,
                        help_text="Every assignment of this type must name an internal sponsor.",
                    ),
                ),
                (
                    "requires_organization",
                    models.BooleanField(
                        default=False,
                        help_text="Every assignment of this type must name the agency, school or company.",
                    ),
                ),
                (
                    "max_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Longest assignment allowed; empty for no limit.",
                        null=True,
                        verbose_name="Maximum duration (days)",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "person type",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExternalOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("inactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("hr", "HR feed"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("agency", "Staffing agency"),
                            ("school", "School / program"),
                            ("vendor", "Vendor / company"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The catalog vendor this company is, when it is one.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_organizations",
                        to="catalog.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "external organization",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("inactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("hr", "HR feed"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        help_text="Preferred first name, when it differs.",
                        max_length=100,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The HR key. Empty for people HR does not employ.",
                        max_length=30,
                        verbose_name="Employee ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "work_location",
                    models.CharField(
                        blank=True, help_text="Site or campus.", max_length=150
                    ),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("separation_date", models.DateField(blank=True, null=True)),
                (
                    "on_leave",
                    models.BooleanField(
                        default=False,
                        help_text="On a leave of absence: expected access is suspended while set.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="people.person",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="The HealthIAM login of this person, for the few who have one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "people",
                "ordering": ["last_name", "first_name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PersonIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("npi", "NPI"),
                            ("state_license", "State license"),
                            ("student_id", "Student ID"),
                            ("badge", "Badge"),
                            ("vendor_id", "Vendor / agency ID"),
                            ("former_employee_id", "Former employee ID"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "issued_by",
                    models.CharField(
                        blank=True, help_text="School, state, agency...", max_length=150
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "identifier",
                "ordering": ["kind", "value"],
            },
        ),
        migrations.CreateModel(
            name="PersonName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                ("preferred_name", models.CharField(blank=True, max_length=100)),
                (
                    "used_from",
                    models.DateField(
                        blank=True, help_text="Empty when unknown.", null=True
                    ),
                ),
                ("used_until", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[("hr", "HR feed"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="former_names",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "former name",
                "ordering": ["-used_until", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PersonTypeCoordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_assignments",
                        to="people.persontype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person type coordinator",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.AddField(
            model_name="persontype",
            name="coordinators",
            field=models.ManyToManyField(
                blank=True,
                related_name="coordinated_types",
                through="people.PersonTypeCoordinator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PositionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("primary", "Primary"), ("alternate", "Alternate")],
                        default="primary",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Empty for open-ended.", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Working title, when the position's is not it.",
                        max_length=200,
                    ),
                ),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transfer", "Transfer to another position"),
                            ("separation", "Left the organization"),
                            ("contract_end", "Contract or rotation ended"),
                            ("expired", "Expired"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("hr", "HR feed"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The agency, school or company this person comes from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="people.externalorganization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="people.person",
                    ),
                ),
                (
                    "person_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="people.persontype",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="orgs.position",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The internal person responsible for this assignment.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sponsored_assignments",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "position assignment",
                "ordering": ["-start_date", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="externalorganization",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_external_organization_name",
                violation_error_message="An organization with this name already exists.",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                django.db.models.functions.text.Lower("last_name"),
                django.db.models.functions.text.Lower("first_name"),
                name="people_person_name_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee_id", ""), _negated=True),
                fields=("employee_id",),
                name="unique_person_employee_id",
                violation_error_message="Another person already has this employee ID.",
            ),
        ),
        migrations.AddConstraint(
            model_name="personidentifier",
            constraint=models.UniqueConstraint(
                models.F("kind"),
                django.db.models.functions.text.Lower("value"),
                condition=models.Q(("kind", "other"), _negated=True),
                name="unique_identifier_value_per_kind",
                violation_error_message="Another person already has this identifier.",
            ),
        ),
        migrations.AddIndex(
            model_name="personname",
            index=models.Index(
                django.db.models.functions.text.Lower("last_name"),
                django.db.models.functions.text.Lower("first_name"),
                name="people_personname_name_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="persontypecoordinator",
            constraint=models.UniqueConstraint(
                fields=("person_type", "user"),
                name="unique_coordinator_per_person_type",
                violation_error_message="That user already coordinates this type.",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="assignment_end_after_start",
                violation_error_message="The end date cannot be before the start date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionassignment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("kind", "primary")),
                expressions=[
                    ("person", "="),
                    (
                        apps.people.models.DateRange(
                            "start_date",
                            "end_date",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="exclude_overlapping_primary_assignments",
                violation_error_message="This person already holds a primary position during that period.",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionassignment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("person", "="),
                    ("position", "="),
                    (
                        apps.people.models.DateRange(
                            "start_date",
                            "end_date",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="exclude_overlapping_position_assignments",
                violation_error_message="This person already holds that position during that period.",
            ),
        ),
    ]
