# Generated by Django 5.2.17 on 2026-09-22 16:35

import apps.people.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_dynamic_ad_groups"),
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("grant", "Grant"), ("exclusion", "Exclusion")],
                        default="grant",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Empty until removed.", null=True
                    ),
                ),
                (
                    "ticket_ref",
                    models.CharField(
                        blank=True,
                        help_text="Request or ticket number.",
                        max_length=100,
                        verbose_name="Ticket",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True,
                        help_text="Why this person needs it beyond their position.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "access_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_grants",
                        to="catalog.accesslevel",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved it: the manager, the sponsor or the application owner.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_access",
                        to="people.person",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_grants",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "person access",
                "verbose_name_plural": "person access",
                "ordering": ["-start_date", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="person_access_end_after_start",
                        violation_error_message="The end date cannot be before the start date.",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            ("person", "="),
                            ("access_level", "="),
                            ("kind", "="),
                            (
                                apps.people.models.DateRange(
                                    "start_date",
                                    "end_date",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(
                                        inclusive_lower=True, inclusive_upper=True
                                    ),
                                ),
                                "&&",
                            ),
                        ],
                        name="exclude_overlapping_person_access",
                        violation_error_message="This person already has that row for the period.",
                    ),
                ],
            },
        ),
    ]
