# Generated by Django 5.2.17 on 2026-09-23 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_personaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="network_username",
            field=models.CharField(
                blank=True,
                help_text="The AD account name (sAMAccountName) or UPN. Links the person's directory accounts when their employee ID cannot.",
                max_length=256,
                verbose_name="Network username",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("network_username", ""), _negated=True),
                fields=("network_username",),
                name="unique_person_network_username",
                violation_error_code="unique",
                violation_error_message="Another person already has this network username.",
            ),
        ),
    ]
