# Generated by Django 5.2.17 on 2026-09-22 22:42

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntraGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Tenant ID"),
                ),
                ("object_id", models.UUIDField(unique=True, verbose_name="Object ID")),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Still returned by the sync."),
                ),
                ("inactivated_at", models.DateTimeField(blank=True, null=True)),
                ("display_name", models.CharField(db_index=True, max_length=256)),
                ("description", models.TextField(blank=True)),
                ("mail", models.EmailField(blank=True, max_length=254)),
                ("mail_nickname", models.CharField(blank=True, max_length=256)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("mail_security", "Mail-enabled security"),
                            ("m365", "Microsoft 365"),
                            ("distribution", "Distribution list"),
                            ("other", "Other"),
                        ],
                        default="security",
                        max_length=20,
                    ),
                ),
                (
                    "membership",
                    models.CharField(
                        choices=[("assigned", "Assigned"), ("dynamic", "Dynamic")],
                        default="assigned",
                        max_length=10,
                    ),
                ),
                ("membership_rule", models.TextField(blank=True)),
                (
                    "is_assignable_to_role",
                    models.BooleanField(
                        default=False,
                        help_text="Members can be granted Entra admin roles.",
                        verbose_name="Role-assignable",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cloud", "Cloud"),
                            ("synced", "Synced from AD"),
                            ("converted", "Converted to cloud"),
                        ],
                        default="cloud",
                        max_length=10,
                    ),
                ),
                (
                    "on_premises_sam_account_name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        verbose_name="On-premises account name",
                    ),
                ),
                (
                    "on_premises_security_identifier",
                    models.CharField(blank=True, max_length=184, verbose_name="On-premises SID"),
                ),
                (
                    "on_premises_domain_name",
                    models.CharField(blank=True, max_length=256, verbose_name="On-premises domain"),
                ),
                (
                    "on_premises_last_sync_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_in_entra_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Created in Entra ID"),
                ),
            ],
            options={
                "verbose_name": "Entra group",
                "ordering": ["display_name", "pk"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("display_name"),
                        name="entra_group_lname_idx",
                    ),
                    models.Index(
                        django.db.models.functions.text.Lower("on_premises_sam_account_name"),
                        name="entra_group_lsam_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EntraSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(choices=[("all", "Groups")], default="all", max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("previewed", "Previewed (dry run)"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "server",
                    models.CharField(
                        blank=True,
                        help_text="Graph endpoint that answered.",
                        max_length=255,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Tenant ID"),
                ),
                ("tenant_name", models.CharField(blank=True, max_length=256)),
                (
                    "directory_sync_enabled",
                    models.BooleanField(
                        blank=True,
                        help_text="The tenant synchronizes from on-premises AD: a hybrid tenant.",
                        null=True,
                        verbose_name="Directory sync on",
                    ),
                ),
                ("directory_last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("log", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entra sync run",
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
