# Generated by Django 5.2.17 on 2026-09-22 22:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entra", "0001_initial"),
        ("people", "0002_personaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrasyncrun",
            name="sign_in_activity",
            field=models.CharField(
                blank=True,
                help_text="Why sign-in activity could not be read, if not.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="entrasyncrun",
            name="scope",
            field=models.CharField(
                choices=[
                    ("all", "Groups and accounts"),
                    ("groups", "Groups only"),
                    ("accounts", "Accounts only"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="EntraAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Tenant ID"),
                ),
                ("object_id", models.UUIDField(unique=True, verbose_name="Object ID")),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Still returned by the sync."),
                ),
                ("inactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "upn",
                    models.CharField(
                        db_index=True,
                        max_length=256,
                        verbose_name="User principal name",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=256)),
                ("given_name", models.CharField(blank=True, max_length=150)),
                ("surname", models.CharField(blank=True, max_length=150)),
                ("mail", models.EmailField(blank=True, max_length=254)),
                ("other_mails", models.JSONField(blank=True, default=list)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("department", models.CharField(blank=True, max_length=150)),
                ("company_name", models.CharField(blank=True, max_length=150)),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Employee ID",
                    ),
                ),
                ("user_type", models.CharField(default="Member", max_length=20)),
                ("creation_type", models.CharField(blank=True, max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("synced", "Synced from AD"),
                            ("cloud", "Cloud member"),
                            ("converted", "Cloud member (was synced)"),
                            ("guest", "Guest"),
                            ("external", "External member"),
                        ],
                        db_index=True,
                        default="cloud",
                        max_length=10,
                    ),
                ),
                (
                    "identity_provider",
                    models.CharField(
                        blank=True,
                        help_text="Issuer of the federated identity a guest uses.",
                        max_length=150,
                    ),
                ),
                (
                    "external_user_state",
                    models.CharField(blank=True, max_length=40, verbose_name="Invitation"),
                ),
                (
                    "external_user_state_changed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "account_enabled",
                    models.BooleanField(default=True, help_text="Sign-in allowed in Entra ID."),
                ),
                (
                    "created_in_entra_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Created in Entra ID"),
                ),
                (
                    "last_sign_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last interactive sign-in"
                    ),
                ),
                (
                    "last_non_interactive_sign_in_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_successful_sign_in_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="The latest of the sign-in timestamps Entra ID reports.",
                        null=True,
                        verbose_name="Last sign-in",
                    ),
                ),
                (
                    "sign_in_activity_known",
                    models.BooleanField(
                        default=False,
                        help_text="The last sync could read sign-in activity for this account.",
                    ),
                ),
                (
                    "on_premises_immutable_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "on_premises_object_guid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Decoded from onPremisesImmutableId; matches the AD account mirror.",
                        null=True,
                        verbose_name="On-premises objectGUID",
                    ),
                ),
                (
                    "on_premises_security_identifier",
                    models.CharField(blank=True, max_length=184, verbose_name="On-premises SID"),
                ),
                (
                    "on_premises_sam_account_name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        verbose_name="On-premises account name",
                    ),
                ),
                (
                    "on_premises_domain_name",
                    models.CharField(blank=True, max_length=256, verbose_name="On-premises domain"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin account"),
                            ("service", "Service account"),
                            ("shared", "Shared / generic"),
                            ("unknown", "Unknown"),
                        ],
                        default="user",
                        help_text="Set by hand: the directory does not say what an account is for.",
                        max_length=10,
                    ),
                ),
                (
                    "link_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employee_id", "By employee ID"),
                            ("email", "By e-mail"),
                            ("manual", "By hand"),
                        ],
                        max_length=12,
                    ),
                ),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entra_accounts",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entra account",
                "ordering": ["upn", "pk"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("upn"),
                        name="entra_account_lupn_idx",
                    )
                ],
            },
        ),
    ]
