# Generated by Django 5.2.17 on 2026-09-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entra", "0002_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrasyncrun",
            name="user_group",
            field=models.CharField(blank=True, max_length=256, verbose_name="User group"),
        ),
        migrations.AlterField(
            model_name="entrasyncrun",
            name="scope",
            field=models.CharField(
                choices=[
                    ("all", "Logins, groups and accounts"),
                    ("users", "Logins only"),
                    ("groups", "Groups only"),
                    ("accounts", "Accounts only"),
                ],
                default="all",
                max_length=10,
            ),
        ),
    ]
