# Generated by Django 5.2.17 on 2026-09-23 02:20

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_dynamic_entra_groups"),
        ("entra", "0003_logins"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntraGroupRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pattern",
                    models.CharField(
                        help_text="Case-insensitive glob matched against the group's display name, e.g. SG-*",
                        max_length=200,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Lowest number wins among routes to the same kind of target. An application always outranks a service, whatever the numbers say.",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, help_text="Why this route exists.", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Usually a service; any application is allowed.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entra_group_routes",
                        to="catalog.application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entra group route",
                "ordering": ["priority", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("pattern"),
                        name="unique_entra_group_route_pattern",
                        violation_error_message="A route for this pattern already exists.",
                    )
                ],
            },
        ),
    ]
