# Generated by Django 5.2.17 on 2026-09-17 22:58

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ADGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_guid",
                    models.UUIDField(unique=True, verbose_name="objectGUID"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="sAMAccountName.",
                        max_length=256,
                        verbose_name="Group name",
                    ),
                ),
                (
                    "cn",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Common name"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "distinguished_name",
                    models.CharField(db_index=True, max_length=1024),
                ),
                (
                    "group_type",
                    models.IntegerField(
                        default=0, help_text="Raw groupType bit field."
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("builtin_local", "Builtin local"),
                            ("global", "Global"),
                            ("domain_local", "Domain local"),
                            ("universal", "Universal"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("distribution", "Distribution"),
                        ],
                        default="security",
                        max_length=20,
                    ),
                ),
                (
                    "managed_by_dn",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="Managed by"
                    ),
                ),
                ("when_changed", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("inactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AD group",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        name="directory_adgroup_lname_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DirectorySyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "Users and groups"),
                            ("users", "Users only"),
                            ("groups", "Groups only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("previewed", "Previewed (dry run)"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "server",
                    models.CharField(
                        blank=True, help_text="Server that answered.", max_length=255
                    ),
                ),
                (
                    "group_dn",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="User group DN"
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("log", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "directory sync run",
                "ordering": ["-created_at"],
            },
        ),
    ]
