# Generated by Django 5.2.17 on 2026-09-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_adgrouproute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adgrouproute",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Lowest number wins among routes to the same kind of target. An application always outranks a service, whatever the numbers say.",
            ),
        ),
    ]
