# Generated by Django 5.2.17 on 2026-09-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_route_priority_help"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directorysyncrun",
            options={
                "ordering": ["-created_at", "-pk"],
                "verbose_name": "directory sync run",
            },
        ),
    ]
