# Generated by Django 5.2.17 on 2026-09-22 16:54

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_sync_run_stable_ordering"),
        ("people", "0002_personaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorysyncrun",
            name="scope",
            field=models.CharField(
                choices=[
                    ("all", "Users, groups and accounts"),
                    ("users", "Users only"),
                    ("groups", "Groups only"),
                    ("accounts", "Accounts only"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DirectoryAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_guid",
                    models.UUIDField(unique=True, verbose_name="objectGUID"),
                ),
                (
                    "sam_account_name",
                    models.CharField(
                        db_index=True, max_length=256, verbose_name="Account name"
                    ),
                ),
                (
                    "upn",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="User principal name"
                    ),
                ),
                (
                    "distinguished_name",
                    models.CharField(db_index=True, max_length=1024),
                ),
                ("given_name", models.CharField(blank=True, max_length=150)),
                ("surname", models.CharField(blank=True, max_length=150)),
                ("display_name", models.CharField(blank=True, max_length=256)),
                ("mail", models.EmailField(blank=True, max_length=254)),
                ("title", models.CharField(blank=True, max_length=150)),
                ("department", models.CharField(blank=True, max_length=150)),
                (
                    "manager_dn",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="Manager DN"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Employee ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Not disabled in AD."),
                ),
                ("account_expires", models.DateTimeField(blank=True, null=True)),
                ("when_created", models.DateTimeField(blank=True, null=True)),
                ("when_changed", models.DateTimeField(blank=True, null=True)),
                (
                    "last_logon_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="lastLogonTimestamp, which replicates only every 9-14 days.",
                        null=True,
                        verbose_name="Last logon",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin account"),
                            ("service", "Service account"),
                            ("shared", "Shared / generic"),
                            ("unknown", "Unknown"),
                        ],
                        default="user",
                        help_text="Set by hand: the directory does not say what an account is for.",
                        max_length=10,
                    ),
                ),
                (
                    "link_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employee_id", "By employee ID"),
                            ("manual", "By hand"),
                        ],
                        max_length=12,
                    ),
                ),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Still returned by the sync."
                    ),
                ),
                ("inactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="directory_accounts",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "AD account",
                "ordering": ["sam_account_name", "pk"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("sam_account_name"),
                        name="directory_account_lsam_idx",
                    )
                ],
            },
        ),
    ]
