# Generated by Django 5.2.17 on 2026-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_directoryaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryaccount",
            name="kind_source",
            field=models.CharField(
                blank=True,
                choices=[("rule", "By rule"), ("manual", "By hand")],
                help_text="Blank: no rule matched, so the account is a plain user unless set by hand.",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="directoryaccount",
            name="kind",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin account"),
                    ("service", "Service account"),
                    ("shared", "Shared / generic"),
                    ("unknown", "Unknown"),
                ],
                default="user",
                help_text="What the account is for. The directory does not say: a kind comes from the AD_ACCOUNT_KIND_PATTERNS rules or is set by hand, and a hand-set kind always wins.",
                max_length=10,
            ),
        ),
    ]
