# Generated by Django 5.2.17 on 2026-09-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_directoryaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="adgroup",
            name="cloud_object_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Object ID of the Entra ID group this AD group is the written-back copy of.",
                null=True,
                verbose_name="Written back from Entra group",
            ),
        ),
        migrations.AddField(
            model_name="adgroup",
            name="object_sid",
            field=models.CharField(
                blank=True, db_index=True, max_length=184, verbose_name="objectSid"
            ),
        ),
    ]
