# Generated by Django 5.2.17 on 2026-09-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0007_adgroup_entra_pairing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryaccount",
            name="link_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person_number", "By person number"),
                    ("employee_id", "By employee ID"),
                    ("former_id", "By former employee ID"),
                    ("username", "By username"),
                    ("paired", "Through its Entra ID account"),
                    ("email", "By e-mail"),
                    ("manual", "By hand"),
                ],
                max_length=20,
            ),
        ),
    ]
