# Generated by Django 5.2.17 on 2026-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0008_account_link_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="directoryaccount",
            name="person_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="As AD_PERSON_NUMBER_ATTRIBUTE holds it, typos included.",
                max_length=64,
                verbose_name="Person number",
            ),
        ),
    ]
