# Generated by Django 5.2.17 on 2026-09-17 16:19

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("website", models.URLField(blank=True)),
                ("support_phone", models.CharField(blank=True, max_length=50)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                (
                    "support_portal_url",
                    models.URLField(blank=True, verbose_name="Support portal URL"),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, help_text="User-facing URL.")),
                (
                    "admin_url",
                    models.URLField(blank=True, verbose_name="Admin / support URL"),
                ),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Tier 1 – Mission critical"),
                            (2, "Tier 2 – Business critical"),
                            (3, "Tier 3 – Important"),
                            (4, "Tier 4 – Low impact"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("pilot", "Pilot"),
                            ("active", "Active"),
                            ("retiring", "Retiring"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("go_live_date", models.DateField(blank=True, null=True)),
                ("sunset_date", models.DateField(blank=True, null=True)),
                (
                    "holds_phi",
                    models.BooleanField(default=False, verbose_name="Holds PHI"),
                ),
                (
                    "holds_pii",
                    models.BooleanField(default=False, verbose_name="Holds PII"),
                ),
                (
                    "holds_clinical_records",
                    models.BooleanField(
                        default=False, verbose_name="Holds clinical records"
                    ),
                ),
                (
                    "holds_pci",
                    models.BooleanField(
                        default=False, verbose_name="Holds PCI (card data)"
                    ),
                ),
                (
                    "holds_employee_data",
                    models.BooleanField(
                        default=False, verbose_name="Holds employee data"
                    ),
                ),
                (
                    "holds_research_data",
                    models.BooleanField(
                        default=False, verbose_name="Holds research data"
                    ),
                ),
                (
                    "data_description",
                    models.TextField(
                        blank=True,
                        help_text="What data the system holds, in plain language.",
                    ),
                ),
                (
                    "host_location",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site data center"),
                            ("colo", "Colocation"),
                            ("aws", "AWS"),
                            ("azure", "Azure"),
                            ("gcp", "Google Cloud"),
                            ("vendor_hosted", "Vendor hosted / SaaS"),
                            ("hybrid", "Hybrid"),
                            ("other", "Other"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                (
                    "host_details",
                    models.CharField(
                        blank=True,
                        help_text="Region, cluster, data center, or SaaS tenant.",
                        max_length=255,
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("sso_saml", "SSO (SAML)"),
                            ("sso_oidc", "SSO (OIDC)"),
                            ("ad_ldap", "AD / LDAP"),
                            ("local", "Local accounts"),
                            ("none", "No authentication"),
                            ("other", "Other"),
                        ],
                        default="sso_saml",
                        max_length=20,
                    ),
                ),
                (
                    "mfa_enforced",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="MFA enforced"
                    ),
                ),
                (
                    "rto_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recovery time objective.",
                        null=True,
                        verbose_name="RTO (hours)",
                    ),
                ),
                ("maintenance_window", models.CharField(blank=True, max_length=200)),
                (
                    "dr_status",
                    models.CharField(
                        choices=[
                            ("none", "No DR plan"),
                            ("planned", "DR plan documented"),
                            ("tested", "DR plan tested"),
                            ("na", "Not applicable"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="DR status",
                    ),
                ),
                ("contract_renewal_date", models.DateField(blank=True, null=True)),
                ("cost_center", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationAnalyst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyst_assignments",
                        to="catalog.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyst_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "user__last_name", "user__first_name"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="analysts",
            field=models.ManyToManyField(
                blank=True,
                related_name="analyst_applications",
                through="catalog.ApplicationAnalyst",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=150)),
                (
                    "team",
                    models.CharField(
                        blank=True, help_text="Team or organization.", max_length=150
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to a login so this person gets Application Owner rights where named.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for vendor-side contacts; leave empty for internal staff.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="catalog.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("vendor_support", "Vendor support"),
                            ("vendor_account_manager", "Vendor account manager"),
                            ("vendor_technical", "Vendor technical contact"),
                            ("internal_sme", "Internal subject-matter expert"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_contacts",
                        to="catalog.application",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_links",
                        to="catalog.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "contact__name"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="business_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_owned",
                to="catalog.contact",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="technical_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technically_owned",
                to="catalog.contact",
            ),
        ),
        migrations.CreateModel(
            name="SupportTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="1 = first line of support."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Team or group, e.g. Service Desk.", max_length=150
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "hours",
                    models.CharField(
                        blank=True, help_text="e.g. 24x7, M–F 7a–6p", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tiers",
                        to="catalog.application",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_tiers",
                        to="catalog.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["application__name", "level"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="catalog.vendor",
            ),
        ),
        migrations.CreateModel(
            name="AccessLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "access_model",
                    models.CharField(
                        choices=[
                            ("ad_group", "AD group membership"),
                            ("in_app", "Configured in the application"),
                            ("ticket", "Ticket to an assignment team"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ad_group_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="AD group"
                    ),
                ),
                (
                    "in_app_instructions",
                    models.TextField(
                        blank=True,
                        help_text="How to grant this level inside the app.",
                        verbose_name="In-app instructions",
                    ),
                ),
                (
                    "ticket_assignment_team",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Ticket assignment team",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_levels",
                        to="catalog.application",
                    ),
                ),
            ],
            options={
                "ordering": ["application__name", "sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "name"),
                        name="unique_access_level_name_per_application",
                        violation_error_message="This application already has a level with that name.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApplicationAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(max_length=150)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.application",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "application aliases",
                "ordering": ["alias"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("alias"),
                        models.F("application"),
                        name="unique_alias_per_application",
                        violation_error_message="This alias already exists for the application.",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="applicationanalyst",
            constraint=models.UniqueConstraint(
                fields=("application", "user"), name="unique_analyst_per_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationcontact",
            constraint=models.UniqueConstraint(
                fields=("application", "contact", "role"),
                name="unique_application_contact_role",
                violation_error_message="That contact already has this role on the application.",
            ),
        ),
        migrations.AddConstraint(
            model_name="supporttier",
            constraint=models.UniqueConstraint(
                fields=("application", "level"),
                name="unique_support_tier_level_per_application",
                violation_error_message="This application already has that tier level.",
            ),
        ),
    ]
