# Generated by Django 5.2.17 on 2026-09-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="kind",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("service", "Infrastructure service"),
                ],
                db_index=True,
                default="application",
                help_text="Services hold AD groups that are not tied to a vendor application.",
                max_length=20,
            ),
        ),
    ]
