# Generated by Django 5.2.17 on 2026-09-19 22:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_application_kind"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accesslevel",
            index=models.Index(
                django.db.models.functions.text.Lower("ad_group_name"),
                name="catalog_level_adgroup_idx",
            ),
        ),
    ]
