# Generated by Django 5.2.17 on 2026-09-20 01:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_accesslevel_catalog_level_adgroup_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslevel",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Added by hand"),
                    ("route", "Managed by an AD group route"),
                    ("adopted", "Taken over from a route"),
                ],
                db_index=True,
                default="manual",
                help_text="Route-managed levels are created and retired automatically; adopting the group by hand takes one over.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="dynamic_ad_groups",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Hold an access level automatically for every active AD group this application's routes claim and nobody has adopted by hand.",
                verbose_name="Dynamic AD groups",
            ),
        ),
        migrations.AddIndex(
            model_name="accesslevel",
            index=models.Index(
                django.db.models.functions.text.Lower("ad_group_name"),
                models.F("source"),
                models.F("is_active"),
                name="catalog_level_claim_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesslevel",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("ad_group_name"),
                condition=models.Q(("source", "route")),
                name="unique_route_level_per_group",
                violation_error_message="Another application already holds this AD group by route.",
            ),
        ),
    ]
