# Generated by Django 5.2.17 on 2026-09-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_dynamic_ad_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslevel",
            name="entra_group_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Entra group object ID",
            ),
        ),
        migrations.AddField(
            model_name="accesslevel",
            name="entra_group_name",
            field=models.CharField(
                blank=True,
                help_text="The group's display name when the level was saved; the object ID decides.",
                max_length=256,
                verbose_name="Entra group",
            ),
        ),
        migrations.AlterField(
            model_name="accesslevel",
            name="access_model",
            field=models.CharField(
                choices=[
                    ("ad_group", "AD group membership"),
                    ("entra_group", "Entra ID group membership"),
                    ("in_app", "Configured in the application"),
                    ("ticket", "Ticket to an assignment team"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
