# Generated by Django 5.2.17 on 2026-09-23 02:19

import django.db.models.functions.text
from django.db import migrations, models

# Route-managed cloud-group levels. The AD constraint is narrowed to AD-group levels -- a cloud
# group's level has a blank `ad_group_name`, so the old condition allowed one route-held cloud
# group in the whole catalog -- and cloud groups get their own, keyed by object ID. Reversing
# this migration recreates the old constraint, which fails while two or more cloud-group levels
# are held by route.


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_accesslevel_entra_group"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accesslevel",
            name="unique_route_level_per_group",
        ),
        migrations.AddField(
            model_name="application",
            name="dynamic_entra_groups",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Hold an access level automatically for every active cloud group this application's Entra group routes claim, can be granted, and nobody has adopted by hand.",
                verbose_name="Dynamic Entra groups",
            ),
        ),
        migrations.AlterField(
            model_name="accesslevel",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Added by hand"),
                    ("route", "Managed by a group route"),
                    ("adopted", "Taken over from a route"),
                ],
                db_index=True,
                default="manual",
                help_text="Route-managed levels are created and retired automatically; adopting the group by hand takes one over.",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="accesslevel",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("ad_group_name"),
                condition=models.Q(("access_model", "ad_group"), ("source", "route")),
                name="unique_route_level_per_group",
                violation_error_message="Another application already holds this AD group by route.",
            ),
        ),
        migrations.AddConstraint(
            model_name="accesslevel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("access_model", "entra_group"), ("source", "route")
                ),
                fields=("entra_group_id",),
                name="unique_entra_route_level_per_group",
                violation_error_message="Another application already holds this Entra group by route.",
            ),
        ),
    ]
