# Generated by Django 5.2.17 on 2026-09-17 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "access_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_defaults",
                        to="catalog.accesslevel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defaults",
                        to="orgs.position",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "position__code",
                    "access_level__application__name",
                    "access_level__name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "access_level"),
                        name="unique_default_per_position_level",
                        violation_error_message="This position already has that access level by default.",
                    )
                ],
            },
        ),
    ]
