# Generated by Django 5.2.17 on 2026-09-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="kind",
            field=models.CharField(
                choices=[
                    ("departments", "Departments"),
                    ("job_codes", "Job codes"),
                    ("positions", "Positions"),
                    ("people", "People"),
                ],
                max_length=20,
            ),
        ),
    ]
